orders/urls.py
from django.urls import path

from . import views

from .views import (
    delete_from_cart,
    cart_view,
    clean_cart,
    add_to_cart,
    fulfill_order,
    add_topping,
    clear_topping
)

urlpatterns = [
    path("", views.menu, name="menu"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("signup", views.signup_view, name="signup"),
    path('cart', views.cart_view, name='cart'),
    path(r'item/delete/(<order_id>[-\w]+)/', delete_from_cart, name='delete_item'),
    path(r'cart/clear', clean_cart, name='clean_cart'),
    path(r'item/add/(<item_id>[-\w]+)/', add_to_cart, name='add'),
    path(r'login/?next=/item/add/(<item_id>[-\w]+)/', add_to_cart, name='add'),
    path(r'cart/', fulfill_order, name='fulfill'),
    path(r'clr_tp/<int:order_id>/', clear_topping, name='clear_topping'),
    path(r'add_topping/<int:order_id>(/d<item_type>[^/]+)/', add_topping, name='add_topping'),
    path("success", views.success_view, name="success"),
    path('my_orders', views.my_orders_view, name='my_orders'),
    path('directions', views.directions_view, name='directions')
]

pizza/urls.py
from django.contrib import admin
from django.urls import include, path

from orders import views

urlpatterns = [
    path("", include("orders.urls")),
    path("spontini/", admin.site.urls),
]

orders/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
# Create your models here.


class Topping(models.Model):
    topping = models.CharField(max_length=64)

    def __str__(self):
        return f"{self.topping}"


class Product(models.Model):
    choices = [
        ('L', 'LARGE'),
        ('S', 'SMALL'),
        ('SING', 'SINGLE')
    ]
    price = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    name = models.CharField(max_length=64, default=0)
    type = models.CharField(max_length=64, default=0)
    size = models.CharField(choices=choices, max_length=64, default=0)

    def __str__(self):
        return f"{self.name} {self.type}, {self.size}, price {self.price}"


class Order(models.Model):
    choices = [
        ('Sausage', 'Sausage'),
        ('Pepperoni', 'Pepperoni'),
        ('Mushrooms', 'Mushrooms'),
        ('Onions', 'Onions'),
        ('Ham', 'Ham'),
        ('Canadian', 'Canadian Bacon'),
        ('Spinach', 'Spinach'),
        ('Tomato', 'Tomato & Basil'),
        ('Green', 'Green Pepper'),
        ('Anchovies', 'Anchovies'),
        ('Artichoke', 'Artichoke'),
        ('Buffalo', 'Buffalo Chicken'),
        ('Eggplant', 'Eggplant'),
        ('Zucchini', 'Zucchini'),
        ('Fresh', 'Fresh Garlic')
    ]
    items = models.ManyToManyField(Product)
    date_ordered = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    toppingchoice = MultiSelectField(choices=choices, null=True, blank=True)
    fulfilled = models.BooleanField(default=False)

    def __str__(self):
        return f"#{self.pk} {self.owner} ordered {self.items.first()}, {self.toppingchoice} on {self.date_ordered}," \
               f"fulfilled: {self.fulfilled}, topping: {self.toppingchoice}"

    def get_order_items(self):
        ordered = str(self.items.name)
        return ordered

    def clean_fulfilled(self):
        fulfilled = Order.objects.filter(fulfilled=True)
        for order in fulfilled:
            order.delete()


class CompletedOrder(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)

orders/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect
from .models import Topping, Product, Order, CompletedOrder
from django.db.utils import OperationalError
from django.contrib.auth import login, logout
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.contrib import messages
# Create your views here.
try:
    def menu(request):
        context = {
            "menu": Product.objects.all(),
            "toppings": Topping.objects.all(),
            "regular": Product.objects.filter(name='Regular Pizza'),
            "sicilian": Product.objects.filter(name='Sicilian Pizza'),
            "pasta": Product.objects.filter(name='Pasta'),
            "salad": Product.objects.filter(name='Salads'),
            "platter": Product.objects.filter(name='Dinner Platters'),
            "user": request.user,
            "users": render(request, 'users/login.html'),
            "sub": Product.objects.filter(name='Sub'),
            "product": Product.objects.all()
        }
        return render(request, "orders/menu.html", context)

    def signup_view(request):
        if request.method == 'POST':
            form = UserCreationForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request, f"Account created for {username}!")
                # log the user in
                return redirect('menu')
        else:
            form = UserCreationForm()
        return render(request, 'users/signup.html', {'form': form})

    def login_view(request):
        if request.method == "POST":
            form = AuthenticationForm(data=request.POST)
            if form.is_valid():
                user = form.get_user()
                login(request, user)
                messages.success(request, f"Welcome, {user}. Thanks for logging in.")
                return redirect('menu')
        else:
            form = AuthenticationForm()

        return render(request, 'users/login.html', {'form': form})


    def logout_view(request):
        logout(request)
        return redirect("login")

    def success_view(request):
        return redirect("orders/success.html")

except OperationalError:
    pass

@login_required(login_url='login')
def cart_view(request):
    order = Order.objects.filter(owner=request.user.id, fulfilled=False)
    owner = request.user.username
    total_price = []
    order_numb = []
    item_id = []

    # if order exists
    if order:
        for order in order:
            # adding id in this Order
            item_id.extend([order.id])
            user_order = order
            # access order items
            user_order_items = user_order.items.all()
            # add them to the list
            total_price.extend(product.price for product in user_order_items)
            # access whole order from where we can get topping info and order id
            order_numb.append(order)
    # calculating cart total
    total_price = sum(total_price)

    context = {
        "owner": owner,
        "total_price": total_price,
        "item_id": item_id,
        "toppings": Topping.objects.all(),
        "order_numb": order_numb,
    }
    return render(request, "orders/cart.html", context)


@login_required(login_url='login')
def my_orders_view(request):
    orders = Order.objects.filter(owner=request.user.id, fulfilled=True).all().order_by("-date_ordered")

    return render(request, 'orders/my_orders.html', {'orders': orders})


@login_required(login_url='login')
def delete_from_cart(request, order_id):
    # getting order instance by its id
    product = Order.objects.filter(pk=order_id)
    if product.exists():
        product.delete()
    return redirect(reverse('cart'))


@login_required(login_url='login')
def add_to_cart(request, item_id):
    # get the user
    buyer = User.objects.filter(id=request.user.id).first()
    # get the instance of a product by its id
    product = Product.objects.get(pk=item_id)
    # create order for the user and save
    newOrder = Order(owner=buyer)
    newOrder.save()
    # associate this order with the product
    newOrder.items.add(product)
    messages.success(request, f"{product} added to cart.")

    return redirect(reverse('menu'))


@login_required(login_url='login')
def clean_cart(request):
    delete = Order.objects.filter(owner=request.user.id, fulfilled=False)
    if delete.exists():
        for item in delete:
            item.delete()
    return redirect(reverse('cart'))

@login_required(login_url='login')
def add_topping(request, order_id, item_type):
    if request.method == "POST":
        top = request.POST.get('topselect')
        if top:
            order = Order.objects.filter(pk=order_id).first()
            topping_list = []
            print(top)
            # function checks how many toppings were chosen
            n = str(item_type[0])
            if n in item_type:
                # get already selected toppings
                selected = order.toppingchoice
                # add them to list of selected toppings
                topping_list.append(top)
                topping_list.extend(selected)
                if len(topping_list) < int(n):
                    order.toppingchoice = topping_list
                    order.save()
                elif len(topping_list) == int(n):
                    order.toppingchoice = topping_list
                    order.save()
                    topping_list.clear()
                else:
                    topping_list.clear()
    return redirect(reverse('cart'))


@login_required(login_url='login')
def clear_topping(request, order_id):
    order = Order.objects.filter(pk=order_id).first()
    order.toppingchoice = []
    order.save()
    return redirect(reverse('cart'))


@login_required(login_url='login')
def fulfill_order(request):
    items_to_order = Order.objects.filter(owner=request.user.id, fulfilled=False)
    if items_to_order.exists():
        for order in items_to_order:
            order.fulfilled = True
            order.save()
            CompletedOrder(order=order).save()
    return render(request, "orders/success.html")


def directions_view(request):
    return render(request, "orders/directions.html")

orders/templates/orders/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'orders/css/main.css' %}">
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
    </div>
    {% block head %}
    {% endblock %}
</head>

<div class="container">
    {% if user.is_authenticated %}
        <row>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand px-5" href="{% url 'menu' %}">Domuzcuk's pizza</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
            <div class="menu-items d-flex justify-content-center">
            <a class="px-4 mt-3 menu-items" href="{% url "cart" %}">Shopping Cart</a>
            <a class="px-4 mt-3 menu-items" href="{% url "my_orders" %}">My Orders</a>
            <a class="px-4 mt-3 menu-items" href="{% url 'directions' %}">Directions</a>
            <a class="logout px-3 mt-3 menu-items" href="{% url "logout" %}">Log out</a>
            <p class="ml-5 mt-3 log-as">Logged as: {{ user.username.capitalize }}</p>
            </div>
        </nav></row>
    {% endif %}
    {% block body %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
<script src="{% static 'orders/js/script.js' %}"></script>

</html>

orders/templates/orders/cart.html
<!DOCTYPE html>
<html lang="en">
{% extends "orders/base.html" %}
<head>
    {% block head %}
    <title>Shopping cart</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.9/dist/css/bootstrap-select.min.css">
    {% endblock %}
</head>
{% block body %}
    <p class="heading-cart mb-1"> {{ owner.capitalize }}'s Shopping Cart: </p>
    <ul>
    {% if order_numb %}
        <table class="table table-hover cart">
        <tr>
            <th>#</th><th>Order</th><th>Price </th><th>Actions</th><th>Topping</th>
        </tr>
        {% for order in order_numb %}
            <!-- Items chosen -->
            {% for item in order.items.all %}
                <tr class="order-row">
                <td>{{ forloop.parentloop.counter }}.</td>
                <td>
                    <li class="order-item">{{ item.name }} {{ item.type }}, {{ item.get_size_display.capitalize }}</td>
                    <td>{{ item.price }} </td>
                    <td><a href="{% url 'delete_item' order.id %}">Delete item</a></td>
                <!-- showing chosen toppings -->
                     {% if 'topping' in item.type and order.toppingchoice is not None %}
                        <td class="w-25"> <p class="chosen-toppings">{{ order.toppingchoice }}</p>
                     <!-- Select toppings -->
                        <!-- Passing order id with submitted topping -->
                        <form method="post" action="{% url 'add_topping' order.id item.type %}">
                        {% csrf_token %}
                        <select name="topselect" class="custom-select mr-sm-2 select-topping-field">
                            {% if order.toppingchoice in toppings %}
                                    <option selected>{{order.toppingchoice}}</option>
                            {% else %}
                                <option selected disabled>Select Topping</option>
                            {% endif %}
                            {% for topping in toppings %}
                                <option value={{ topping }}>{{ topping }}</option>
                            {% endfor %}
                        </select>
                        <button type="submit" class="btn btn-primary mt-3 choose-topping">Add</button>
                        <button class="btn btn-primary mt-3 clear-topping"><a class="button clr" href="{% url 'clear_topping' order.id %}">Clear</a></button>
                        </form>
                        </td>
                     {% else %} <td></td>
                    {% endif %}
                    </li>
                </tr>
            {% endfor %}
        {% endfor %}
        <tr><td></td>
        <td class="bold">Total:</td><td class="bold">{{ total_price }}</td>
            <td><a href="{% url 'clean_cart'%}">Clean cart</a></td><td></td></tr>
        </table>
    </ul>
    <a id="make-order-link" href="{% url "fulfill" %}" class="btn btn-success btn-lg order float-right">Order</a>
    {% else %}
        <p class="empty">Your shopping car is empty!</p>
    {% endif %}
{% endblock %}
</body>
</html>

orders/templates/orders/directions.html
{% extends 'orders/base.html' %}
<head>
    <title>Directions to Domuzcuk's Pizza</title>
</head>
{% block body %}
    <h2>Location and Directions</h2>
    <a href="https://www.google.ru/maps/place/Koc+University/@41.20207,29.0719155,15.62z/data=!4m5!3m4!1s0x409fe093fb4f1e2f:0xb51b89285c845350!8m2!3d41.20543!4d29.0724115?hl=en">Google Maps</a>
    <p class="mt-2">We're open for you at Koc University, Istanbul.</p>
    <p>Located at Ford's Square. Come enjoy our pizza!</p>
    <img src="https://i.pinimg.com/originals/91/e8/3b/91e83b036d200f5a6b30d9544ce569d1.jpg">
{% endblock %}

orders/templates/orders/menu.html
<!DOCTYPE html>
{% extends "orders/base.html" %}
<html lang="en">
<head>{% block head %}
    <title>Menu</title> {% endblock %}
</head>
<body>
{% block body %}
    {% if user.is_authenticated %}
    {% else %}
        <p>To make an order, please <a href="{% url "login" %}">log in</a>
        or <a href="{% url "signup" %}">register</a>.</p>
    {% endif %}
    <h1>Our menu</h1>
    <div class="col-10 menu-category mx-auto"><div class="mx-auto col-9">
            <a href="#regular-pizza">Regular Pizza | </a> <a href="#sicilian-pizza">Sizilian Pizza | </a><a href="#subs">Subs | </a>
        <a href="#pastas">Pastas | </a> <a href="#salads">Salads | </a> <a href="#dinner-platters">Dinner Platters </a></div>
    <h3 id="regular-pizza">Regular Pizza</h3>
        <table class="table table-hover">
            <th>Type</th>
            <th>Small</th> <th>Large</th>
            {% for Pizza in regular %}
                {% if Pizza.size == 'S' or Pizza.size == 'SING' %}<tr>
                <td width="50%">{{ Pizza.type }}</td>
                    <td width="25%">{{ Pizza.price }} <a class="addToCart" href="{% url 'add' Pizza.id %}">+</a></td>
                    {% elif Pizza.size == 'L' %}
                    <td width="25%">{{ Pizza.price }}  <a class="addToCart" href="{% url 'add' Pizza.id %}">+</a></td></tr>
                {% endif %}
            {% endfor %}
        </table>
        <h3 id="sicilian-pizza"> Sicilian Pizza</h3>
        <table class="table table-hover">
            <th>Type</th>
            <th>Small</th> <th>Large</th>

            {% for SizPizza in sicilian %}
                {% if SizPizza.size == 'S' or SizPizza.size == 'SING' %}
                <tr>
                <td width="50%">{{ SizPizza.type }} </td>
                    <td  width="25%">{{ SizPizza.price }} <a class="add-cart" href="{% url 'add' SizPizza.id %}">+</a></td>
                    {% elif SizPizza.size == 'L' %}
                    <td width="25%">{{ SizPizza.price }} <a class="add-cart" href="{% url 'add' SizPizza.id %}">+</a></td></tr>
                {% endif %}
            {% endfor %}
        </table>
        <h3> Toppings </h3>
            <ul class="list-group list-group">
                {% for topping in toppings %}
                        <li class="list-group-item">{{ topping.topping }} </li>
                {% endfor %}
            </ul>
        <h3 id="subs">Subs</h3>
            <table class="table table-hover table-striped">
                <th>Type</th>
                    <th>Small</th><th>Large</th>
                 {% for subs in sub %}
                        {% if subs.size == 'S' or subs.size == 'SING' %}<tr>
                            <td width="50%">{{ subs.type }} </td>
                            <td width="25%">{{ subs.price }} <a href="{% url 'add' subs.id %}">+</a></td>
                            {% elif subs.size == 'L' %}
                            <td width="25%">
                            {{ subs.price }} <a href="{% url 'add' subs.id %}">+</a>
                            </td></tr>
                        {% endif %}
                {% endfor %}
            </table>
        <h3 id="pastas"> Pastas </h3>
            <ul class="list-group">
                {% for pasta in pasta %}
                        <li class="list-group-item">{{ pasta.type }} {{ pasta.price }}<a href="{% url 'add' pasta.id %}">+</a> </li>
                {% endfor %}
            </ul>
        <h3 id="salads"> Salads </h3>
            <ul class="list-group">
                {% for salad in salad %}
                        <li class="list-group-item">{{ salad.type }} {{ salad.price }} <a href="{% url 'add' salad.id %}">+</a> </li>
                {% endfor %}
            </ul>

        <h3 id="dinner-platters"> Dinner Platters</h3>
            <ul class="list-group">
                {% for platter in platter %}
                    {% if platter.size == 'S' or platter.size == 'SING' %}
                        <li class="list-group-item">{{ platter.type }}
                          Small ${{ platter.price }} <a href="{% url 'add' platter.id %}">+</a>
                            {% elif platter.size == 'L' %}Large ${{ platter.price }} <a href="{% url 'add' platter.id %}">+</a></li>
                    {% endif %}
                {% endfor %}
            </ul>

<div class="mx-auto col-9 my-5">
        <a href="#regular-pizza">Regular Pizza | </a> <a href="#sicilian-pizza">Sizilian Pizza | </a><a href="#subs">Subs | </a>
    <a href="#pastas">Pastas | </a> <a href="#salads">Salads | </a> <a href="#dinner-platters">Dinner Platters </a>
</div>
    </div>
{% endblock %}
</body>
</html>

orders/templates/orders/my_orders.html
{% extends "orders/base.html" %}
{% block body %}
    <table class="table table-hover cart">
<ol>
    <tr>
            <th>#</th><th>Order</th><th>Price</th><th>Date</th>
        </tr>
    {% for order in orders %}
        <tr>
        <td> {{ forloop.counter }}.</td>
            {% for product in order.items.all %}
                <td> {{ product.name }} {{ product.type }} {{ product.get_size_display.capitalize }} </td>
                    <td>{{ product.price }}</td>{% endfor %}
        <td> {{ order.date_ordered }}</td>
        </tr>
    {% endfor %}
</ol>
    </table>
{% endblock %}

orders/templates/orders/success.html
<!DOCTYPE html>
{% extends 'orders/base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% block body %}
    <h3>Thank you for ordering at Domuzcuk's pizza!</h3>
    <p>Your order is on the way.</p>
     <a href="{% url "menu" %}">Back to main page</a>
{% endblock %}
</body>
</html>